spring.application.name=lima-segura-backend
spring.datasource.url=jdbc:postgresql://localhost:5433/lima_segura
spring.datasource.username=lima_segura_user
spring.datasource.password=lima_segura_pass
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.jpa.show-sql=true